name: view-graph
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip=19.2.2
  - jupyter=1.0.0
  - holoviews=1.12.3
  - bokeh=1.2.0
  - geoviews=1.6.2
  - autopep8=1.4.4
  - polyline=1.4.0
  - pip:
      - maturin==0.7.7
